public class AirtableWrapper {
    private String test;
    private String test1;
    private String test2;
    private String test3;
    private String test4;
    
    public String setTest(String test) {
        return this.Test= test;
    }
    
    public String setTest1(String test1) {
        return this.Test1= test1;
    }
    
    public String setTest2(String test2) {
        return this.Test2= test2;
    }
    
    public String setTest3(String test3) {
        return this.Test3= test3;
    }
    
     public String setTest4(String test4) {
        return this.Test4= test4;
    }
    
}