/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 08-15-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class ContactController {
/*
@AuraEnabled(cacheable=true)
 public static List<Contact> getContactList(){
    return [SELECT Id, Name, AccountId, Phone
            FROM Contact 
            LIMIT 5];
 }
 @AuraEnabled(cacheable=true)
 public static List<Contact> getConDetailsBasedOnName(String searchKey){
    String qName = '%' + searchKey + '%';
    return [SELECT Id, Name, AccountId, Phone
            FROM Contact 
            WHERE NAME LIKE :qName
            LIMIT 5];
 }*/
}